#!/bin/bash

# search_r1_tool_call: standard tool-calling version of Search-R1 -- Qwen3-4B
# Uses Qwen3's native tool-call format and built-in thinking mode.
#
# -- Step 1: Prepare data --
#   cd /workspace/src/clean_code_for_rl/slime_0224_2026/slime
#   python /workspace/src/clean_code_for_rl/Search-R1/scripts/data_process/qa_search_train_merge_standard.py \
#       --local_dir /workspace/src/clean_code_for_rl/Search-R1/data/nq_hotpotqa_train_standard \
#       --data_sources nq,hotpotqa \
#       --model_family qwen3
#   # Output: .../nq_hotpotqa_train_standard/train_standard.parquet
#
# -- Step 2: Convert Qwen3-4B to Megatron torch_dist format --
#   cd /workspace/src/clean_code_for_rl/slime_0224_2026/slime
#   source scripts/models/qwen3-4B.sh
#   PYTHONPATH=/workspace/Megatron-LM python tools/convert_hf_to_torch_dist.py \
#       ${MODEL_ARGS[@]} \
#       --hf-checkpoint /workspace/.cache/huggingface/hub/models--Qwen--Qwen3-4B/snapshots/1cfa9a7208912126459214e8b04321603b3df60c \
#       --save /lc3T/Qwen3-4B_torch_dist
#
# -- Step 3: (Optional) Start the local retrieval server --
#   cd /workspace/src/clean_code_for_rl/Search-R1/examples/search-r1
#   python local_search_server.py --port 8000
#
# -- Step 4: Run this script --

pkill -9 sglang
sleep 3
ray stop --force
pkill -9 ray
pkill -9 python
sleep 3
pkill -9 ray
pkill -9 python

set -ex

export TMPDIR="/workspace/tmp"
export HF_HOME="/workspace/.cache/huggingface"
export XDG_CACHE_HOME="/workspace/.cache"
export XDG_DATA_HOME="/workspace/.local/share"
export XDG_STATE_HOME="/workspace/.local/state"

export PYTHONBUFFERED=16
export WANDB_KEY="local-643dfe5b804d35d8ab5aeba347f30f4ee0c6ca6f"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)"

source "${SCRIPT_DIR}/../../scripts/models/qwen3-4B.sh"

HF_CKPT=/workspace/.cache/huggingface/hub/Qwen3-4B
MEGATRON_CKPT=/workspace/.cache/huggingface/hub/Qwen3-4B_torch_dist
RL_SAVE=/lc3T/Qwen3-4B_slime

CKPT_ARGS=(
   --hf-checkpoint ${HF_CKPT}
   --ref-load ${MEGATRON_CKPT}
   --save ${RL_SAVE}
   --save-interval 20
   # --load ${RL_SAVE}   # uncomment to resume from a checkpoint
)

ROLLOUT_ARGS=(
   # Dataset generated by qa_search_train_merge_standard.py (includes "tools" column)
   --prompt-data /workspace/src/clean_code_for_rl/Search-R1/data/nq_hotpotqa_train_standard/train_standard.parquet
   --input-key prompt
   --label-key reward_model
   --tool-key tools
   --apply-chat-template
   --apply-chat-template-kwargs '{"enable_thinking":true}'
   --rollout-shuffle
   --num-rollout 5
   --rollout-batch-size 8
   --n-samples-per-prompt 2
   --rollout-max-response-len 2048

   --rollout-temperature 0.7

   # eval args
   # --eval-interval 25
   # --eval-prompt-data nq_test /root/Search-R1/data/nq_hotpotqa_train_standard/test_standard.parquet@[0:3000]
   # --eval-input-key prompt
   # --eval-label-key reward_model
   # --eval-tool-key tools
   # --n-samples-per-eval-prompt 1

   --global-batch-size 16
   --balance-data
)

PERF_ARGS=(
   --tensor-model-parallel-size 2
   --sequence-parallel
   --pipeline-model-parallel-size 1
   --context-parallel-size 1
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1

   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 1

   --use-dynamic-batch-size
   --max-tokens-per-gpu 9216
)

GRPO_ARGS=(
   --advantage-estimator grpo
   --use-kl-loss
   --kl-loss-coef 0.001
   --kl-loss-type low_var_kl
   --entropy-coef 0.00
   --eps-clip 0.2
   --eps-clip-high 0.28
)

OPTIMIZER_ARGS=(
   --optimizer adam
   --lr 1e-6
   --lr-decay-style constant
   --weight-decay 0.01
   --adam-beta1 0.9
   --adam-beta2 0.98
)

WANDB_ARGS=(
   --use-wandb
   --wandb-project slime-dev
   --wandb-group search-r1-tool-call_qwen3-4B-test
   --wandb-key ${WANDB_KEY}
   --wandb-host https://wandb.glm.ai
)

SGLANG_ARGS=(
   --rollout-num-gpus-per-engine 2
   --sglang-mem-fraction-static 0.7
)

MISC_ARGS=(
   --attention-dropout 0.0
   --hidden-dropout 0.0
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   --attention-backend flash
)

CUSTOM_ARGS=(
   # Reuse geo3k_vlm_multi_turn's generic multi-turn rollout unchanged
   --custom-generate-function-path examples.geo3k_vlm_multi_turn.rollout.generate
   # Reward function for standard tool-call format
   --custom-rm-path examples.search_r1_tool_call.reward.reward_func
   # Config: max_turns, search backend, reward weights
   --custom-config-path examples/search_r1_tool_call/config.yaml
)

export MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
ray start --head --node-ip-address ${MASTER_ADDR} --num-gpus 8 --disable-usage-stats

# PYTHONPATH explanation:
#   ${REPO_ROOT}                      -> makes examples.geo3k_vlm_multi_turn and
#                                        examples.search_r1_tool_call importable
#   ${REPO_ROOT}/examples/search-r1   -> exposes local_search_server and
#                                        google_search_server as bare imports
#                                        inside env_search.py
RUNTIME_ENV_JSON="{
  \"env_vars\": {
    \"PYTHONPATH\": \"/workspace/Megatron-LM:${REPO_ROOT}:${REPO_ROOT}/examples/search-r1\",
    \"CUDA_DEVICE_MAX_CONNECTIONS\": \"1\",
    \"WANDB_API_KEY\": \"${WANDB_KEY}\",
    \"WANDB_BASE_URL\": \"https://wandb.glm.ai\"
  }
}"

ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json="${RUNTIME_ENV_JSON}" \
   -- python3 train.py \
   --actor-num-nodes 1 \
   --actor-num-gpus-per-node 4 \
   --rollout-num-gpus 4 \
   --colocate \
   ${MODEL_ARGS[@]} \
   ${CKPT_ARGS[@]} \
   ${ROLLOUT_ARGS[@]} \
   ${OPTIMIZER_ARGS[@]} \
   ${GRPO_ARGS[@]} \
   ${WANDB_ARGS[@]} \
   ${PERF_ARGS[@]} \
   ${SGLANG_ARGS[@]} \
   ${MISC_ARGS[@]} \
   ${CUSTOM_ARGS[@]}
