#!/bin/bash

# search_r1_tool_call: standard tool-calling version of Search-R1
# Uses Qwen's native <tool_call>{JSON}</tool_call> format instead of custom
# <search>/<answer> XML tags, and geo3k_vlm_multi_turn's rollout infrastructure.
#
# Prerequisites:
#   1. Generate the standard tool-call dataset (--model_family qwen2.5 adds ReAct instructions):
#      python Search-R1/scripts/data_process/qa_search_train_merge_standard.py \
#          --local_dir /root/Search-R1/data/nq_hotpotqa_train_standard \
#          --data_sources nq,hotpotqa \
#          --model_family qwen2.5
#
#   2. Start the local retrieval server (if using search_backend=local):
#      See examples/search-r1/README.md for setup instructions.

pkill -9 sglang
sleep 3
ray stop --force
pkill -9 ray
pkill -9 python
sleep 3
pkill -9 ray
pkill -9 python

set -ex

export PYTHONUNBUFFERED=1

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." &>/dev/null && pwd)"

source "${SCRIPT_DIR}/../../scripts/models/qwen2.5-3B.sh"

CKPT_ARGS=(
   --hf-checkpoint /root/Qwen2.5-3B/
   --ref-load /root/Qwen2.5-3B_torch_dist/
   # --load /root/Qwen2.5-3B_slime/
   # --save /root/Qwen2.5-3B_slime/
   # --save-interval 20
)

ROLLOUT_ARGS=(
   # Dataset generated by qa_search_train_merge_standard.py (includes "tools" column)
   --prompt-data /root/Search-R1/data/nq_hotpotqa_train_standard/train_standard.parquet
   --input-key prompt
   --label-key reward_model
   --tool-key tools            # injects WEB_SEARCH_TOOL schema into apply_chat_template
   --apply-chat-template
   --rollout-shuffle
   --num-rollout 3000
   --rollout-batch-size 32
   --n-samples-per-prompt 8
   --rollout-max-response-len 512
   --rollout-temperature 1

   # eval args
   # --eval-interval 25
   # --eval-prompt-data nq_test /root/Search-R1/data/nq_hotpotqa_train/test_with_tools.parquet@[0:3000]
   # --eval-input-key prompt
   # --eval-label-key reward_model
   # --eval-tool-key tools
   # --n-samples-per-eval-prompt 1

   --global-batch-size 256
   --balance-data
)

PERF_ARGS=(
   --tensor-model-parallel-size 2
   --sequence-parallel
   --pipeline-model-parallel-size 1
   --context-parallel-size 1
   --expert-model-parallel-size 1
   --expert-tensor-parallel-size 1

   --recompute-granularity full
   --recompute-method uniform
   --recompute-num-layers 1

   --use-dynamic-batch-size
   --max-tokens-per-gpu 9216
)

GRPO_ARGS=(
   --advantage-estimator grpo
   --use-kl-loss
   --kl-loss-coef 0.001
   --kl-loss-type low_var_kl
   --entropy-coef 0.00
   --eps-clip 0.2
   --eps-clip-high 0.28
)

OPTIMIZER_ARGS=(
   --optimizer adam
   --lr 1e-6
   --lr-decay-style constant
   --weight-decay 0.01
   --adam-beta1 0.9
   --adam-beta2 0.98
)

WANDB_ARGS=(
   # --use-wandb
   # --wandb-project slime-dev
   # --wandb-group search-r1-tool-call_qwen2.5-3B
   # --wandb-key ${WANDB_KEY}
)

SGLANG_ARGS=(
   --rollout-num-gpus-per-engine 2
   --sglang-mem-fraction-static 0.7
)

MISC_ARGS=(
   --attention-dropout 0.0
   --hidden-dropout 0.0
   --accumulate-allreduce-grads-in-fp32
   --attention-softmax-in-fp32
   --attention-backend flash
)

CUSTOM_ARGS=(
   # Reuse geo3k_vlm_multi_turn's generic multi-turn rollout unchanged
   --custom-generate-function-path examples.geo3k_vlm_multi_turn.rollout.generate
   # New reward function adapted for standard tool-call format
   --custom-rm-path examples.search_r1_tool_call.reward.reward_func
   # Config: max_turns, search backend, reward weights
   --custom-config-path examples/search_r1_tool_call/config.yaml
)

export MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
ray start --head --node-ip-address ${MASTER_ADDR} --num-gpus 8 --disable-usage-stats

# PYTHONPATH explanation:
#   ${REPO_ROOT}                      → makes examples.geo3k_vlm_multi_turn and
#                                        examples.search_r1_tool_call importable
#   ${REPO_ROOT}/examples/search-r1   → exposes local_search_server and
#                                        google_search_server as bare imports
#                                        inside env_search.py
RUNTIME_ENV_JSON="{
  \"env_vars\": {
    \"PYTHONPATH\": \"/root/Megatron-LM/:${REPO_ROOT}:${REPO_ROOT}/examples/search-r1\",
    \"CUDA_DEVICE_MAX_CONNECTIONS\": \"1\"
  }
}"

ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json="${RUNTIME_ENV_JSON}" \
   -- python3 train.py \
   --actor-num-nodes 1 \
   --actor-num-gpus-per-node 4 \
   --rollout-num-gpus 4 \
   --colocate \
   ${MODEL_ARGS[@]} \
   ${CKPT_ARGS[@]} \
   ${ROLLOUT_ARGS[@]} \
   ${OPTIMIZER_ARGS[@]} \
   ${GRPO_ARGS[@]} \
   ${WANDB_ARGS[@]} \
   ${PERF_ARGS[@]} \
   ${SGLANG_ARGS[@]} \
   ${MISC_ARGS[@]} \
   ${CUSTOM_ARGS[@]}
